#ifndef SPO_LAB3_ERROR_H
#define SPO_LAB3_ERROR_H

#define SUCCESS 0
#define ERR_SERVER_SOCKET_OPEN 1
#define ERR_SERVER_SOCKET_SETNAME 2
#define ERR_SERVER_SOCKET_BIND 3
#define ERR_SERVER_SOCKET_LISTEN 4
#define ERR_SERVER_ACCEPT 5
#define ERR_SERVER_SEND_BOOK 6
#define ERR_CLIENT_OPEN_SOCKET 7
#define ERR_CLIENT_CONNECT 8
#define ERR_CLIENT_CONNECT_SERVER 9
#define ERR_CLIENT_TERMINAL_ERRPR 10

#endif //SPO_LAB3_ERROR_H
